# Generated by Django 5.0.2 on 2024-02-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etudiant',
            new_name='etudiants',
        ),
        migrations.RemoveField(
            model_name='sessioncours',
            name='session_id',
        ),
    ]
