# Generated by Django 5.0.2 on 2024-02-10 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_rename_etudiant_etudiants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessioncours',
            name='formateur',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='formulaire',
            old_name='heure_fermeture',
            new_name='derniereconnexion',
        ),
        migrations.RenameField(
            model_name='formulaire',
            old_name='heure_ouverture',
            new_name='premiereconnexion',
        ),
        migrations.RemoveField(
            model_name='formulaire',
            name='statut',
        ),
        migrations.AddField(
            model_name='formulaire',
            name='difficulte',
            field=models.CharField(default='facile', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulaire',
            name='pourcentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulaire',
            name='progression',
            field=models.CharField(default='compris', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé')], max_length=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.session'),
        ),
        migrations.DeleteModel(
            name='etudiants',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='SessionCours',
        ),
    ]
